### ISSUE TITLE
Window resize vs. Header

### ISSUE THREAD

**Issue by skerbis** [skerbis/naloga#3]
Ich weiß nicht ob es ein js problem ist. Konnte es noch nicht genau prüfen. 
Wenn man das Fenster verkleinert. Reagiert der Header träge und passt sich erst der Fenstergröße nach dem scrollen wieder an. Problem mit sticky?

**Comment by darwin26** [comment]
check ich mal... danke

**Comment by darwin26** [comment]
gestetet (OSX)
- FF
- Safari
- Chrome

kann ich nicht reproduzieren.

**Comment by skerbis** [comment]
Hat sich erledigt. Da war bei mir irgendwo ein bug
